[General]
server = True
seed = 81025
blinding = False

[Processing]
segment_epochs = True

[Paths]
# Root of the NAS share (mounted path on mac, UNC on windows)
server_root_mac = /Volumes/Hummel-Data
server_root_windows = \\sv-nas1.rcp.epfl.ch\Hummel-Data

# Please customize your local root (only)!
local_root = /add/your/local/path