[General]
server = True
seed = 81025
blinding = False

[Processing]
segment_epochs = True

[Paths]
# Root of server
server_root = /add/your/server/path

# Please customize your local root (only)!
local_root = /add/your/local/path